#!/bin/bash

# Get the process IDs of all Gunicorn workers
worker_pids=$(pgrep gunicorn)

# Send a graceful reload signal to each worker
for pid in $worker_pids; do
  echo "Reloading worker $pid"
  kill -HUP $pid
done

echo "Gunicorn gracefully reloaded"
